"""Update User model to support removals

Revision ID: 12e1b92b897f
Revises: 8fb79834c64d
Create Date: 2019-06-12 20:49:48.800718

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '12e1b92b897f'
down_revision = '8fb79834c64d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('flagged_for_deletion', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('last_talked', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('writeups', 'author_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint('writeups_author_id_fkey', 'writeups', type_='foreignkey')
    op.create_foreign_key(None, 'writeups', 'users', ['author_id'], ['discord_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'writeups', type_='foreignkey')
    op.create_foreign_key('writeups_author_id_fkey', 'writeups', 'users', ['author_id'], ['discord_id'], ondelete='CASCADE')
    op.alter_column('writeups', 'author_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('users', 'last_talked')
    op.drop_column('users', 'joined_at')
    op.drop_column('users', 'flagged_for_deletion')
    # ### end Alembic commands ###
