"""remove_blogs

Revision ID: 13d2afe94e48
Revises: 6a56c28c6bf1
Create Date: 2022-09-06 17:29:55.189057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_searchable import drop_trigger
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '13d2afe94e48'
down_revision = '6a56c28c6bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    drop_trigger(conn, "blogs", "search_vector")
    op.drop_index('blogs_tags_array_idx', table_name='blogs')
    op.drop_table('blogs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('creation_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('edit_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.CheckConstraint("slug <> ''::text", name='blogs_slug_nonempty'),
    sa.ForeignKeyConstraint(['author_id'], ['users.discord_id'], name='blogs_author_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='blogs_pkey'),
    sa.UniqueConstraint('slug', name='blogs_slug_key'),
    sa.UniqueConstraint('title', name='blogs_title_key')
    )
    op.create_index('blogs_tags_array_idx', 'blogs', ['tags'], unique=False)
    # ### end Alembic commands ###
