"""Update completedchallenge pkey

Revision ID: 276ab5e9da65
Revises: 9140c8139240
Create Date: 2021-10-29 14:07:36.283627

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '276ab5e9da65'
down_revision = '9140c8139240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('completedchallenges_pkey', 'completedchallenges', type_='primary')
    op.create_primary_key('completedchallenges_pkey', 'completedchallenges', ['discord_id', 'challenge_id', 'season'])
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('completedchallenges_pkey', 'completedchallenges', type_='primary')
    op.create_primary_key('completedchallenges_pkey', 'completedchallenges', ['discord_id', 'challenge_id'])
    pass
    # ### end Alembic commands ###
