"""Add challenge tags and hidden/depreciated flags

Revision ID: 299fc37d1df6
Revises: e3f509844945
Create Date: 2020-10-11 01:04:57.679123

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '299fc37d1df6'
down_revision = 'e3f509844945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('depreciated', sa.Boolean(), nullable=True))
    op.add_column('challenges', sa.Column('hidden', sa.Boolean(), nullable=True))
    op.add_column('challenges', sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True))
    op.execute("UPDATE challenges SET depreciated = false")
    op.execute("UPDATE challenges SET hidden = false")
    op.execute("UPDATE challenges SET tags = '{}'")
    op.alter_column('challenges', 'depreciated', nullable=False)
    op.alter_column('challenges', 'hidden', nullable=False)
    op.alter_column('challenges', 'tags', nullable=False)
    op.create_index('challenge_tags_array_idx', 'challenges', ['tags'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('challenge_tags_array_idx', table_name='challenges')
    op.drop_column('challenges', 'tags')
    op.drop_column('challenges', 'hidden')
    op.drop_column('challenges', 'depreciated')
    # ### end Alembic commands ###
