"""Remove machinedisplay table

Revision ID: 4656bfd26a60
Revises: d00c347994e5
Create Date: 2022-10-01 00:31:47.290937

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '4656bfd26a60'
down_revision = 'd00c347994e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machine_displays')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_displays',
    sa.Column('discord_message_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('machine_hostname', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('discord_message_id', name='machine_displays_pkey')
    )
    # ### end Alembic commands ###
