"""Add tailscale auth table

Revision ID: 591bd09b721f
Revises: 4656bfd26a60
Create Date: 2023-10-03 00:14:02.786600

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '591bd09b721f'
down_revision = '4656bfd26a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tskey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tailcontrol', sa.Text(), nullable=False),
    sa.Column('authstate2', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tskey')
    # ### end Alembic commands ###
