"""Add Blog posts

Revision ID: 8fb79834c64d
Revises: 38952f538172
Create Date: 2019-04-29 01:28:40.440714

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy_searchable import sync_trigger

# revision identifiers, used by Alembic.
revision = "8fb79834c64d"
down_revision = "38952f538172"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    op.create_table(
        "blogs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("tags", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "creation_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "edit_date", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "search_vector",
            sqlalchemy_utils.types.ts_vector.TSVectorType(
                "title", "content", weights={"title": "A", "content": "B"}
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
        sa.UniqueConstraint("title"),
    )
    op.create_index(
        "blogs_tags_array_idx",
        "blogs",
        ["tags"],
        unique=False,
        postgresql_using="gin",
    )

    sync_trigger(conn, "blogs", "search_vector", ["title", "content"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("blogs_tags_array_idx", table_name="blogs")
    op.drop_table("blogs")
    # ### end Alembic commands ###
