"""Add writeup schema

Revision ID: 98b885be8d35
Revises: 85a64ed7293f
Create Date: 2019-03-22 04:18:11.449446

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy_searchable import sync_trigger, sql_expressions

# revision identifiers, used by Alembic.
revision = "98b885be8d35"
down_revision = "85a64ed7293f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    # op.execute("CREATE EXTENSION pg_trgm")

    op.create_table(
        "writeups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("tags", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "search_vector",
            sqlalchemy_utils.types.ts_vector.TSVectorType(
                "title", "content", weights={"title": "A", "content": "B"}
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.discord_id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "writeups_tags_array_idx",
        "writeups",
        ["tags"],
        unique=False,
        postgresql_using="gin",
    )

    op.execute(sql_expressions.statement)

    sync_trigger(conn, "writeups", "search_vector", ["title", "content"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    op.drop_index("writeups_tags_array_idx", table_name="writeups")

    sync_trigger(conn, "writeups", "search_vector", ["title", "content"])

    op.drop_table("writeups")

    # op.execute("DROP EXTENSION pg_trgm")

    # ### end Alembic commands ###
