"""Add bot_notification trigger for challenge completes.

Revision ID: a85ea6887ffa
Revises: 07df328e09b3
Create Date: 2020-10-15 00:56:57.507094

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'a85ea6887ffa'
down_revision = '07df328e09b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("""
    CREATE FUNCTION send_bot_notification() RETURNS trigger as $$
    DECLARE
    BEGIN
    PERFORM pg_notify('bot_notification', (to_jsonb(row_to_json(NEW)) ||
                                           jsonb_object(TG_ARGV))::TEXT);
    RETURN NEW;
    END;
    $$ LANGUAGE plpgsql
    """)

    op.execute("""
    CREATE TRIGGER new_solve_notify AFTER INSERT ON completedchallenges
    FOR EACH ROW EXECUTE PROCEDURE send_bot_notification('type', 'challenge_complete')
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER new_solve_notify ON completedchallenges")
    op.execute("DROP FUNCTION send_bot_notification()")
    # ### end Alembic commands ###
