"""Add Challenges

Revision ID: b0df6f4097b7
Revises: 3ac3a75942b8
Create Date: 2020-09-19 06:31:00.923016

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b0df6f4097b7'
down_revision = '3ac3a75942b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('flag', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flag'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.create_table('completedchallenges',
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discord_id'], ['users.discord_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('discord_id', 'challenge_id')
    )
    op.alter_column('images', 'author_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint('images_author_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'users', ['author_id'], ['discord_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_author_id_fkey', 'images', 'users', ['author_id'], ['discord_id'], ondelete='CASCADE')
    op.alter_column('images', 'author_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_table('completedchallenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###
