"""Add challenge answer/flag stuff

Revision ID: b1d4c25e198d
Revises: 299fc37d1df6
Create Date: 2020-10-13 02:39:02.093322

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b1d4c25e198d'
down_revision = '299fc37d1df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('answer', sa.Text(), nullable=True))
    op.alter_column('challenges', 'flag',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_check_constraint('challenges_flag_answer_distinct',
                               'challenges',
                               '(flag IS NULL) != (answer IS NULL)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('challenges_flag_answer_distinct',
                       'challenges')
    op.alter_column('challenges', 'flag',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('challenges', 'answer')
    # ### end Alembic commands ###
