"""Make title and slug unique

Revision ID: c8b00e4933a6
Revises: ed281d01fb3b
Create Date: 2019-04-09 03:18:27.841298

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c8b00e4933a6'
down_revision = 'ed281d01fb3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'writeups', ['title'])
    op.create_unique_constraint(None, 'writeups', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'writeups', type_='unique')
    op.drop_constraint(None, 'writeups', type_='unique')
    # ### end Alembic commands ###
