"""Add machine display tracker

Revision ID: d00c347994e5
Revises: ac2a0e49a58e
Create Date: 2022-09-26 00:05:38.965124

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'd00c347994e5'
down_revision = 'ac2a0e49a58e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_displays',
    sa.Column('discord_message_id', sa.BigInteger(), nullable=False),
    sa.Column('machine_hostname', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('discord_message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machine_displays')
    # ### end Alembic commands ###
