"""Add challenge search vector

Revision ID: e3f509844945
Revises: 38188dd2243f
Create Date: 2020-09-20 06:17:10.847299

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy_searchable import sync_trigger


# revision identifiers, used by Alembic.
revision = 'e3f509844945'
down_revision = '38188dd2243f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    op.add_column('challenges', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))

    sync_trigger(conn, "challenges", "search_vector", ["title", "content"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sync_trigger(conn, "challenges", "search_vector", ["title", "content"])

    op.drop_column('challenges', 'search_vector')
    # ### end Alembic commands ###
