"""remove_todos

Revision ID: f78a26022069
Revises: 276ab5e9da65
Create Date: 2022-09-06 16:25:19.577355

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy_searchable import sync_trigger
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f78a26022069'
down_revision = '276ab5e9da65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')

    conn = op.get_bind()

    sync_trigger(conn,
                 "challenges", "search_vector", ["title", "content"]
                 )

    sync_trigger(conn,
                 "writeups", "search_vector", ["title", "content"]
                 )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assigned', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('started', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('cancelled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('completed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='todos_pkey')
    )

    conn = op.get_bind()

    sync_trigger(conn,
                 "challenges", "search_vector", ["title", "content"]
                 )

    sync_trigger(conn,
                 "writeups", "search_vector", ["title", "content"]
                 )
    # ### end Alembic commands ###
