"""Add writeup private

Revision ID: fffe37a910ff
Revises: a85ea6887ffa
Create Date: 2020-11-22 13:10:57.204019

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'fffe37a910ff'
down_revision = 'a85ea6887ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writeups', sa.Column('private', sa.Boolean(), nullable=True))
    op.execute("UPDATE writeups SET private = false")
    op.alter_column('writeups', 'private', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writeups', 'private')
    # ### end Alembic commands ###
